### ISSUE TITLE
Zeus Factory tweaks

### ISSUE THREAD

**Issue by AACO** [BourbonWarfare/POTATO#126]
So some notes from a few sessions using Zeus Factory

- Sometimes AI would dismount before their waypoint and get suck in a loop of dismounting/remounting
- Factories wouldn't really "load balance" it would only use the closest factory. Possible solution: set a CBA_missionTime variable on the factory, and just use the most stale factory withing a given radius?
- @zerithsmash doesn't like the current option layout: make it more like the spawn a vic menu?

**Comment by PabstMirror** [comment]
Load balance was just a very basic first draft.
` private _effectiveDistance = (_x distance2d _placeLogic) + 200 * (count (_x getVariable [QGVAR(dispatchQueue), []]));`
Change that 200 to 1000+ and it should work better.
