### ISSUE TITLE
Spectator Improvements/Ramblings

### ISSUE THREAD

**Issue by AACO** [BourbonWarfare/POTATO#136]
- [x] Briefly consider using CBA's round tracking setup
- [x] Refactor the way fired event handlers are attached, to work correctly with vehicles
- [x] Refactor the way icons are built, to work correctly with vehicles
- [x] Expand the group icon ranges, maybe add a few smaller steps
- [x] Post CBA update ensure all languages are applied to spectators
- [x] Separate hiding tags and hiding UI
- [x] Clicking on the unit in the list should jump you to the unit, not focus on the unit. (My thought: one click focus, two clicks jumps)
~Look into allowing spectating zeuses to RC units~ (out of scope for now)

**Comment by zerithsmash** [comment]
Don't really know if "allow spectating zeuses to RC units" is worth it.

On the clicking thing. Do any changes to the list affect actually clicking on a unit? I noticed the other day while spectating you in a test mission that I could click on your vehicle/icon and it would focus on you. Was pretty neat. One click to focus two clicks to jump probably makes the most sense.

**Comment by AACO** [comment]
@zerithsmash 
> Do any changes to the list affect actually clicking on a unit?
No, it'd be local to the list. I think if you're close enough to be clicking on names, you can just maneuver the camera where you need it.
