### ISSUE TITLE
Add runtime validation to assignGear

### ISSUE THREAD

**Issue by AACO** [BourbonWarfare/POTATO#141]
When we're building the loadout array, we need to validate known classes (and log anything that's fucked)

Things we should probably validate:
- [ ] Any empty strings should be dumped
- [ ] Uniform/Vest/Backpack/Headgear should be validated (we only need to validate the random item we pulled)
- [ ] Primary/Launcher/Pistol weapons should be validated (we only need to validate the random item we pulled). Attachments are already validated by the CBA check
- [ ] Magazines should be checked

I don't know how effectively we can validate items as they could be from a couple of configuration roots.

**Comment by PabstMirror** [comment]
I think we could hook into the "save" event in 3den and do the checks then

**Comment by AACO** [comment]
We'd have to fix https://github.com/BourbonWarfare/POTATO/issues/77 first though, right?

**Comment by AACO** [comment]
This is resolved by #161 and #164
