### ISSUE TITLE
Add runtime tool to assign markers

### ISSUE THREAD

**Issue by AACO** [BourbonWarfare/POTATO#147]
Due to some rude people crashing/DCing we could really use a tool to set/change markers during run time. I'm not sure where this tool should live as it lives somewhere between the admin menu and the marker component...

**Comment by Alex6511** [comment]
It would be cool if Platoon/Coy people had some ability to assign markers during the mission. Conditions change a lot and sometimes markers break, so it'd be really cool I think.
