### ISSUE TITLE
Spectator Improvements and Fixes

### ISSUE THREAD

**Issue by AACO** [BourbonWarfare/POTATO#154]
Improvements:
- [x] Separate cam tick into an EachFrame event handler
- [x] Add logic to allow RCing as a spectator Zeus
- [x] Disable keyboard search on tree
- [x] Add readable spectate name
- [x] Make the spectate unit playable (and add like 5 to the framework?)
- [x] Make the terrain/object based slowdown toggleable
- [x] Move the spectator count a little to the left to avoid some of the clipping
- [x] Remove helipad
- [x] Add spectate text chat channel
- [x] Handle advanced grenade throwing
- [x] Handle STHUD name ghosting
- [x] Add compass
- [x] Use ACRE's passthrough
- [x] Better icons for grenades
- [x] Add mission clock to timer
- [x] Look into a full screen map (GPS button to open?)
- [x] Add briefings into spectate
- [x] Add a medical readout
- [x] Update help text for new features

Fixes:
- [x] Fix mid velocity draw color
- [x] Fix unit/group removals. (Add a spectator 'side').
- [x] Normal grenade throw locality?
- [x] Fix medic star in tree

Not to be done/out of scope:
- ~~Look into adding some kind of compass to the UI (deferred)~~
- ~~Look into some kind of zoom functionality (most likely not possible)~~
- ~~Look into transferring all side markers to the spectator side. (doable, but not great for TvT respawns)~~
- ~~Make some of the UI elements save/load state in the profile namespace~~

**Comment by PabstMirror** [comment]
`disableKeyboardSearch = 1;`
