### ISSUE TITLE
AI don't work the same way on the HC versus not on the HC

### ISSUE THREAD

**Issue by TheCandianVendingMachine** [BourbonWarfare/POTATO#198]
I was testing some missions and I found a very curious issue with AI reacting on the Headless Client versus them not on it. It seems that AI on the headless client will not engage back at players who shoot at them, while AI not on the headless client will shoot back in the same circumstances. AI on the HC however will shoot back if you have another HC AI shoot at them via the "Suppress Fire" module.

All tests have been conducted on the BW server with BWMF on all.

Videos of problems:
[Mission: brdn_ai_reveal_problem.Chernarus - No HC module placed](https://youtu.be/9Z4QwgJlDhM)
[Mission: brdn_ai_reveal_problem_2.Chernarus -  HC module placed](https://youtu.be/o69kmZQYQ8w)

Now in my testing I determined that this is probably a locality issue with HC units not getting data from non-HC units, however they will receive data the other way around as showcased in the last test of the second video. I can't test this on Vanilla due to me lacking a server with a headless client

I don't know how to fix this, if we can fix it, or if this is intentional - I just wanted to point out an issue that I discovered.

**Comment by TheCandianVendingMachine** [comment]
I have found a work-around to "fix" the issue. If you make the group leader of a headless-client group a non-HC AI the group will fire back at the player if shot at. Assuming 90 AI with 4 man fireteams, 22 AI would not be on the headless.

I will keep investigating to find the root of the issue.

**Comment by AACO** [comment]
I'm pretty sure transferring the leader transfers the group....

**Comment by TheCandianVendingMachine** [comment]
Yep they do transfer the group. When I tried it the server-admin menu didn't update until after I wrote the issue.

**Comment by TheCandianVendingMachine** [comment]
I have investigated this some more and came to the conclusion that it is the ammo used in each gun which affects the AI's ability to fire back. The following videos show my final tests when I hone in on this conclusion

[Testing default NATO equipment to see if they will react without using loadout.hpp](https://youtu.be/6acczyetED0)

[Testing USA default loadout (RHS Ammo) to see if its a problem with the way we set our loadouts](https://youtu.be/DgQ4Yfa20tw)

[Testing default NATO equipment to see if the same problem appears as above (ARMA 3 Ammo)](https://youtu.be/H6eJS4lUTDw)

[Testing to see if weapon AI is holding affects reaction due to max-range they can engage at (RHS Ammo)](https://youtu.be/lNQDrvG9JgM)

[Testing to see if AI will react if I shoot at them with ARMA 3 ammo. This is where I came up with the idea that it was Ammo configs messing with the AI](https://youtu.be/dYlWBlHmdF0)

[Testing ARMA 3 5.56 against AI to confirm that it is ammo type used](https://youtu.be/RLSYmP_8xnA)

[Testing RHS 5.56 to 100% confirm that it is ammo type that determines AI ability to react](https://youtu.be/CfHp9ibpCSg)

From the last two videos you can see the difference. If the AI reacts at all with RHS ammo it is because I hit them directly, while ARMA 3 ammo will have them react if it comes near them. The reason why this only affects Headless Client units is beyond me, but through empirical data you can see that it does.

As demonstrated in [this video](https://www.youtube.com/watch?v=Qbxv4dhWX-o&feature=youtu.be), the fix to this is to change both `audibleFire` and possibly `dangerRadiusHit` and `dangerRadiusBulletClose` to acceptable levels. For the video example I used default ASR AI values for this test.
