### ISSUE TITLE
Fortify tools may not be issued to people who load lste

### ISSUE THREAD

**Issue by Alex6511** [BourbonWarfare/POTATO#225]
During testing and once during live gameplay we noticed that fortify tools were not issued to Brandon when he loaded in late.

Unknown if the issue also effects jips.

**Comment by AACO** [comment]
Probably a race between our gear system and whatever 'auto' adds the hammer. It's probably better to just add it through the gear scripting.

**Comment by PabstMirror** [comment]
the module only adds the item once to everyone on a side,
so jips won't get it.

this should be fixed at some point, but to be honest for our use it doesn't matter as 1-2 not having it won't matter if the rest of the team has it
