### ISSUE TITLE
update cpr settings

### ISSUE THREAD

**Issue by PabstMirror** [BourbonWarfare/POTATO#311]
ref `https://github.com/acemod/ACE3/pull/7983`
https://github.com/BourbonWarfare/POTATO/blob/master/addons/settings/BW_Settings.sqf#L18

new names:
cprSuccessChanceMin / cprSuccessChanceMax

**Comment by PabstMirror** [comment]
Any quick thoughts on this?
right now we have a flat 0.75 chance (from ace default of 0.4)
ace now allows scaling setting based on blood vol, 
so like [chance of success at min blood vol, chance of success at max blood]

I was thinking of something like [0.75,0.9]?

**Comment by ArgoChris** [comment]
I think our baseline setting is good as well and with how rarely we lose people during CA I think that scale is totally fine - if it scales to the absolute max blood volume level though [0.75,1] may not be a terrible idea, just so we don't end up with that insanely rare edge-case where someone just dies even with blood.
