### ISSUE TITLE
WBK zombies, error in zeus 

### ISSUE THREAD

**Issue by kil0byt3** [BourbonWarfare/POTATO#377]
Mother had this during last AH

`if ((isNull _unit) or (isNull _marker) or !(alive _unit)) exitWith { t>
23:29:52   Error position: <_marker) or !(alive _unit)) exitWith { t>
23:29:52   Error Undefined variable in expression: _marker
23:29:52 File WBK_Zombies\AI\WBK_ShooterZombie.sqf..., line 321
23:29:52 Error in expression <eep 0.3;`

repeats indefinitely for Zeus for entire mission. 

looks like it's an error with the mod itself but need to test w/o our modpack to see if it's caused by something we do

mostly putting this here for myself to track for later but feel free to pick up

![image](https://user-images.githubusercontent.com/39413400/198208725-766afa43-1640-47d3-a8e5-af0ea85fdd78.png)

**Comment by PabstMirror** [comment]
dropped
