### ISSUE TITLE
TOW missiles broken

### ISSUE THREAD

**Issue by DanThomas64** [BourbonWarfare/POTATO#387]
Supposedly broken TOW missiles for vics need investigation.

**Comment by TheCandianVendingMachine** [comment]
i think you need to set these 3 in the relevant turret config: https://github.com/TheCandianVendingMachine/ACE3/blob/6aba4b041d382ed76b5c28b00f3cde9860bcc927/addons/missileguidance/functions/fnc_SACLOS_onFired.sqf#L25

the config is fucky wucky and this should maybe be able to fix it

**Comment by PabstMirror** [comment]
https://github.com/TheCandianVendingMachine/ACE3/blob/6aba4b041d382ed76b5c28b00f3cde9860bcc927/addons/missileguidance/functions/fnc_seekerType_SACLOS.sqf#L40-L41

looks like we actually want `animationSourcePhase` I think??
```
        private _gBody = -deg(_shooter animationSourcePhase _animationSourceBody);
        private _gGun = deg(_shooter animationSourcePhase _animationSourceGun);
```
most vics are
```
			body="mainTurret";
			gun="mainGun";
			animationSourceBody="mainTurret";
			animationSourceGun="mainGun";
```
on cup tows they do
```
				animationSourceBody =  "mainTurret";
				animationSourceGun =   "mainGun";
				body = "main_turret";
				gun = "main_gun";
```

`_shooter animationSource "main_turret"` would also work

**Comment by TheCandianVendingMachine** [comment]
can you make a pr on my branch and i merge? i want to fix this but my dev environment is far from setup
