### ISSUE TITLE
SOG GP smokes not having the same dispersion as vanilla/CUP smoke

### ISSUE THREAD

**Issue by DanThomas64** [BourbonWarfare/POTATO#396]
Title self-evident. S.O.G white smoke GPs do not have the same smoke dispersion as vanilla/CUP smokes we use in session, which makes the weapons from S.O.G not really desirable to use.

It's a bit of an ask, but can you possibly roll out a patch that makes not just UGL GPs but also rifle smoke grenades to use the same dispersion? Thanks in advance.

**Comment by PabstMirror** [comment]
seems like all of the VN gls can load 40mm grenades right now (even the sks 22mm)

using the Smoke Shell (White) - `1Rnd_Smoke_Grenade_shell` 
should use the filled smoke
