### ISSUE TITLE
Safestart Auto-End Module

### ISSUE THREAD

**Issue by AChesheireCat** [BourbonWarfare/POTATO#445]
Blame Kilo, but it would be really nice to have a module that mission makers could place down that allows for them to configure how long safestart would last before it automatically ends. It's a nice QoL feature that some other frameworks have that I've missed but understand that it's not really that important :)

**Comment by AChesheireCat** [comment]
Tempted to close this one since I just found a scripting solution instead.

`// Safe-start Auto-Off at 15mins
// [{ [false] call potato_safeStart_fnc_toggleSafeStart }, [], 900] call CBA_fnc_waitAndExecute;
// waitUntil { !potato_safeStart_safeStartEnabled };

// Safe-start Auto-Off at 10mins
// [{ [false] call potato_safeStart_fnc_toggleSafeStart }, [], 600] call CBA_fnc_waitAndExecute;
// waitUntil { !potato_safeStart_safeStartEnabled };`

**Comment by lambdatiger** [comment]
I still agree with [Pabst on this one](https://github.com/BourbonWarfare/POTATO/pull/447#issuecomment-1775763374), forcing safe start in the event of issues is maybe not optimal. If we wanted to add the ability to have just a checkbox to do that, I think we would also want to have a "safety" that starts off, but any admin can toggle on in case safe start goes sideways.

**Comment by AChesheireCat** [comment]
So, that wasn't the original intention. The spin-off from Kilo was as a result of seeing code from a different framework that fit our use case.

My original idea was that there would be an EDEN placeable module that had attributes that allowed for the MM to set how long they'd like to set their safe-start to auto-off at. It would be a completely optional QoL feature that the MM has to choose to opt in to by placing the module down. Admins would still be able to reenable SafeStart if it needs to go longer, etc.

I've used this exact thing in a different group and it was a lovely feature for an MM. Respectfully, I'm not really understanding the level of pushback considering it's a feature in other popular frameworks and is beloved by those frameworks' users.
