### ISSUE TITLE
Project: True Viking "K-M/90 R GL" grenade launcher sight is broken.

### ISSUE THREAD

**Issue by AChesheireCat** [BourbonWarfare/POTATO#488]
The K-M/90 R GL and G-M/90M GL's sight were broken by one of the PTV patches that I submitted; the specific problem is that when switching the firemode to the grenade launcher, it does not put the player's view to the GL sight and instead leaves it in the default "iron sight" view. As a result, it also prevents the player from ranging the GL and is restricted to whatever ranging the iron sights and/or the scope in use has.

Recommend reverting the GL compat patches that I made until a fix can be made that resolves the sight issue.

Bleh.

**Comment by AChesheireCat** [comment]
For the record, this was reported by Stockton who found it out while testing - the issue appears limited to the K-M/90 R GL and the G-M/90M GL as far as I'm aware.

**Comment by AChesheireCat** [comment]
Also to clarify, the sights work properly when no other mod is loaded, so it's definitely a me problem D:

**Comment by kil0byt3** [comment]
Fixed in #489
