### ISSUE TITLE
Spectate - Players in Vehicles don't show correct kill count/radio info/etc

### ISSUE THREAD

**Issue by kil0byt3** [BourbonWarfare/POTATO#545]
in static

![image](https://github.com/user-attachments/assets/01b80c6b-1274-4d0c-8721-720cdcc78c2e)

vs infantry 

![image](https://github.com/user-attachments/assets/3ffa2e35-64f7-4d72-bb46-892613ae3503)

same thing happens in helicopters/ground vehicles etc

i think this is new maybe related to new ACE features

**Comment by PabstMirror** [comment]
Should be fixed by https://github.com/BourbonWarfare/POTATO/pull/537

**Comment by kil0byt3** [comment]
duplicate https://github.com/BourbonWarfare/POTATO/issues/534
