### ISSUE TITLE
gm marauder - look at cmd missile

### ISSUE THREAD

**Issue by PabstMirror** [BourbonWarfare/POTATO#561]
might be ace or something recent here?

**Comment by lambdatiger** [comment]
It's ACE @TheCandianVendingMachine tried to fix it last Tuesday, but needs 2.18 to do it (bone inheritance w/ `getSelectionBones`).

**Comment by TheCandianVendingMachine** [comment]
yeah pretty much what happens is that the animation source is deeply nested within the turret, but for the marder specifically you can't traverse the animation tree without getting wrong information somewhere; `getSelectionBones` will hopefully help

**Comment by kil0byt3** [comment]
fixed (temp) in above PR, issue to be made on ACE's end
