### ISSUE TITLE
Add an ACE Painkiller "Blister Pack"

### ISSUE THREAD

**Issue by AChesheireCat** [BourbonWarfare/POTATO#582]
Essentially just a lower use-count painkiller bottle - reference convo here: https://github.com/BourbonWarfare/bwmf/pull/203

**Comment by kil0byt3** [comment]
https://discord.com/channels/204621032428929025/1293996766106222612/1297993522091393046

**Comment by AChesheireCat** [comment]
I was JUST gonna comment that LMAOOOO

**Comment by kil0byt3** [comment]
i just don't have time to do it rn but it could be added to bwmf common.hpp just via some use of that, probably, it wouldn't have a unique name or icon but it would work for your purposes

**Comment by AChesheireCat** [comment]
If we're gonna do it, we should probably do it right imo. Plus, Naloxone was already added via POTATO so I'm inclined to keep similar stuff together instead of dispersing it across our various gits.

**Comment by TheCandianVendingMachine** [comment]
that would need to be added to potato regardless. its a config update, so it has to be done mod side. you could technically script a pill bottle to start with less pills, but it would be hacky to do at the loadout level
