### ISSUE TITLE
Add mass paradrop as a reinforcement type

### ISSUE THREAD

**Issue by AACO** [BourbonWarfare/POTATO#59]
Adopt the script I wrote for the "Hold What?" an implement it with a UI element that would allow a Zeus to select a side, a drop vehicle (Mi-8,CH-47,C-130), a drop type (troop,light IFV/APC,light tank destroyer), and finally an ARES LZ and RP.

Questions:
Should we?
Since this could spawn up to 25 units/drop is this something we want readily available?

**Comment by Alex6511** [comment]
I would love this personally.
