### ISSUE TITLE
Zeus HC Units

### ISSUE THREAD

**Issue by zerithsmash** [BourbonWarfare/POTATO#6]
Zerith's ideas for this feature:

- [x] Fireteam for each side: Opfor, Blufor, Indfor, MSV(?)
- [x] Single riflemen and rats for the purpose of manning statics, garrison buildings, etc.
- [x] A few specialist options such as manpads for AAA.
- [x] Groups of 2 infantryman for smaller patrols or ambushes.
- [x] Various pre-crewed vehicles should be available.Still missing BMPs and armed offroads.

Will update as I think of other things.

**Comment by AACO** [comment]
I believe you can create dialogs and whatnot from the module, so it _should_ be pretty easy to kind of do what respawn does (but better). Choose your faction, build your group, spawn them in.

**Comment by AACO** [comment]
Partially resolved by #11 ?

**Comment by PabstMirror** [comment]
It's merged but needs refinement
I need some feedback on what common types of vehicles we want for each side.

**Comment by AACO** [comment]
Forum topic seems like a place for that?

**Comment by AACO** [comment]
PR #15 should give us a decent ability to "reinforce" directly on HCs.

**Comment by zerithsmash** [comment]
Unchecked one thing on the list since a few vehicles are still missing (Like BMPs). I've added/updated my list of things I'd like to see.

**Comment by AACO** [comment]
@zerithsmash the last check mark should probably be it's own task, so I created #16 for it.

**Comment by AACO** [comment]
PR #18 Should resolve our "base" HC needs. PR #19 should give us another fun reinforcement option. Can anyone think of anything else besides the mass garrison that needs to be done for HC?
