### ISSUE TITLE
CUP PVS-14 Night Vision Devices are using the ACE binocular overlay instead of the monocular overlay

### ISSUE THREAD

**Issue by AChesheireCat** [BourbonWarfare/POTATO#604]
Pretty much what the title reads. I noticed that the CUP PVS14 and PVS14_WP NODs both incorrectly display the ACE binocular overlay when used. They should be using the ACE monocular overlay instead.

**Comment by lambdatiger** [comment]
This appears to be a problem with ACE BW (loading just CUP Weapons, ACE BW and CBA), normal ACE has this as a monocular, our version has it as a binocular.

**Comment by PabstMirror** [comment]
https://github.com/acemod/ACE3/pull/10348
will be fixed when we update ace

**Comment by kil0byt3** [comment]
should be fixed tonite
