### ISSUE TITLE
Zeus Sync/Locality/RC Issue

### ISSUE THREAD

**Issue by zerithsmash** [BourbonWarfare/POTATO#92]
We have talked about this before, but I wanted to bring it up again because it may be related to issue #60. 

Basically there is some time once a POTATO unit is spawned that they truly become sync'd and ready to go. Sometimes this never really happens. This is most obvious when trying to get groups to follow their waypoints. Thankfully, AACO added a couple of modules to address this, but I've had mixed results with them.

The best surefire way I've found to resolve this is to RC into a unit. I will RC into a unit and then I can't move them or do any actions for upwards to 10 seconds. That's rare, but it does happen and generally is 1-5 seconds of sync time. Once I do this I can exit the unit and they will be good to go.

This also could be related to the issue in the 9/25/16 coop where the entire serve locked up after I RC'd a unit for the first time in the mission. Once it was sync'd the server recovered, some 30+ seconds later. Unfortunately the lag caused by this got at least 1 person killed.

So any thoughts for solutions to this issue or is this always going to be a product of having zeus based missions?

**Comment by AACO** [comment]
Well, FYI RCing into a unit changes the groups locality to your computer, so that's not really the way we want to "solve" this. And as I've said before, this is mainly a clone of https://github.com/BourbonWarfare/POTATO/issues/71 (at least on the AACOM side). Sometimes the AI will lock up when they're set to combat mode.

**Comment by zerithsmash** [comment]
Is making them local to my computer killing AACOM? Because that would at least explain how they become more responsive afterwards. I wouldn't think me RCing into the group leader would turn off their combat state.

**Comment by AACO** [comment]
No, AACOM covers change in localities (or at least it should).
https://github.com/BourbonWarfare/POTATO/blob/master/addons/aiFrameworks/vcom/functions/fnc_startBrain.sqf#L16
It does "restart" it

**Comment by AACO** [comment]
AACO removed, marking as closed
