### ISSUE TITLE
Potato assignGear vs ArmA gear initialization race condition.

### ISSUE THREAD

**Issue by AACO** [BourbonWarfare/POTATO#94]
It appears that, upon JIPing assignGear races with the normal gear initialization. Due to this race, about 50-80% of JIPs get the vanilla gear, and we get the occasional ACRE sync issue.

**Comment by AACO** [comment]
Can we change https://github.com/BourbonWarfare/POTATO/blob/master/addons/assignGear/CfgEventHandlers.hpp#L13 to post init? and delay it by a frame? Right now we have issues with both JIPs and units that try to use the `F_Gear` override on their init scripting.

**Comment by AACO** [comment]
Even with a frame delay JIPs are still having issues, do we want to try and add a larger delay and hope for the best, or is there any better way to handle this?

**Comment by PabstMirror** [comment]
Shame this is impossible to reproduce localy, 
I've got an idea, I'll try to make a PR later today

**Comment by AACO** [comment]
Semi resolved by #113 ... we could probably use a better solution though...

**Comment by AACO** [comment]
Would the be better executed on the local level with a global cache?
